name: mujic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.2
  on_audio_query: ^2.9.0
  permission_handler: ^12.0.0+1
  provider: ^6.1.5
  path_provider: ^2.1.5
  percent_indicator: ^4.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
